---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: tg-

description: 

conditions:
  allOf:
    - property:
        name: number-prop
        operator: eq
        operands:
            - 3.4
