---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: romapp-flag-1

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - flag:
          name: test-to-delete
          value: "true"
    flagValue: false
